// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCorW2LIupepyXU1XIqsyELt_nTT86FMRY',
    appId: '1:857599916939:web:fa6dae5cfa45bbef454d8e',
    messagingSenderId: '857599916939',
    projectId: 'agrovisionai-19de6',
    authDomain: 'agrovisionai-19de6.firebaseapp.com',
    storageBucket: 'agrovisionai-19de6.firebasestorage.app',
    measurementId: 'G-7DXESMNQWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVAMYc_KUX2GAI7lUOaHqIcbptni0TUk',
    appId: '1:857599916939:android:068680482e0d426e454d8e',
    messagingSenderId: '857599916939',
    projectId: 'agrovisionai-19de6',
    storageBucket: 'agrovisionai-19de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp41t5FFKpTPQ9oRkq2pZ4I8K5hFDbvkI',
    appId: '1:857599916939:ios:411648e0fbce7608454d8e',
    messagingSenderId: '857599916939',
    projectId: 'agrovisionai-19de6',
    storageBucket: 'agrovisionai-19de6.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp41t5FFKpTPQ9oRkq2pZ4I8K5hFDbvkI',
    appId: '1:857599916939:ios:411648e0fbce7608454d8e',
    messagingSenderId: '857599916939',
    projectId: 'agrovisionai-19de6',
    storageBucket: 'agrovisionai-19de6.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCorW2LIupepyXU1XIqsyELt_nTT86FMRY',
    appId: '1:857599916939:web:01410b9102c73bb8454d8e',
    messagingSenderId: '857599916939',
    projectId: 'agrovisionai-19de6',
    authDomain: 'agrovisionai-19de6.firebaseapp.com',
    storageBucket: 'agrovisionai-19de6.firebasestorage.app',
    measurementId: 'G-XE2HNLXY9Q',
  );
}
