"""Add User and Roles

Revision ID: 4a8168f9152e
Revises: cd9aae0b6944
Create Date: 2026-05-31 02:34:21.105809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8168f9152e'
down_revision: Union[str, Sequence[str], None] = 'cd9aae0b6944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = postgresql.ENUM('ADMIN', 'AGRICULTOR', name='userrole')
    userrole_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'AGRICULTOR', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    userrole_enum = postgresql.ENUM('ADMIN', 'AGRICULTOR', name='userrole')
    userrole_enum.drop(op.get_bind())
    # ### end Alembic commands ###
