"""Initial schema

Revision ID: cd9aae0b6944
Revises: 
Create Date: 2026-05-30 18:28:56.333112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd9aae0b6944'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('weather_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('BAJO', 'MODERADO', 'ALTO', 'CRITICO', name='risk_level_enum', create_constraint=True), nullable=False),
    sa.Column('estimated_loss_usd', sa.Float(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('pest_detected', sa.String(length=255), nullable=False),
    sa.Column('pest_type', sa.Enum('DEFOLIADOR', 'BARRENADOR', 'SUCCIONADOR', 'ENFERMEDAD_FUNGICA', 'ENFERMEDAD_BACTERIANA', 'OTRO', name='pest_type_enum', create_constraint=True), nullable=False),
    sa.Column('defoliation_pct', sa.Float(), nullable=False, comment='Porcentaje de defoliación observado (0-100)'),
    sa.Column('beneficial_controllers', sa.Text(), nullable=True, comment='Controladores benéficos identificados'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confianza del diagnóstico (0.0 - 1.0)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_id'), 'diagnoses', ['id'], unique=False)
    op.create_index(op.f('ix_diagnoses_user_id'), 'diagnoses', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'AUDIO', 'TEXT', name='file_type_enum', create_constraint=True), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='URL relativa accesible (ej: /static/uploads/images/...)'),
    sa.Column('local_path', sa.String(length=500), nullable=False, comment='Ruta absoluta en el disco del servidor'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_diagnosis_id'), 'attachments', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_diagnosis_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_diagnoses_user_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
